In [1]:
import numpy as np
import pandas as pd
import os

# g

In [2]:
g_dir = '/home/bio/8oxog/data/feature_esox/g_test_info'

In [3]:
g_datas = []
for file in os.listdir(g_dir):
    g_datas.append(pd.read_csv(os.path.join(g_dir,file)))

FileNotFoundError: [Errno 2] No such file or directory: '/home/bio/8oxog/data/feature_esox/g_test_info'

In [ ]:
g_data = pd.concat(g_datas)
g_data

In [ ]:
TN = np.sum(g_data['class_0'] >= g_data['class_1'])
TN

In [ ]:
FP = np.sum(g_data['class_0'] < g_data['class_1'])
FP

In [ ]:
TN +FP

In [ ]:
spec = TN / (TN + FP)
spec

# 8oxog

In [ ]:
oxog_dir = '/home/bio/8oxog/data/feature_esox/8oxog_test_info'
oxog_datas = []
for file in os.listdir(oxog_dir):
    oxog_datas.append(pd.read_csv(os.path.join(oxog_dir, file)))

In [ ]:
oxog_data = pd.concat(oxog_datas)
oxog_data

In [ ]:
TP = np.sum(oxog_data['class_0'] <= oxog_data['class_1'])
TP

In [ ]:
FN = np.sum(oxog_data['class_0'] > oxog_data['class_1'])
FN

In [ ]:
recall = TP / (TP + FN)
recall

# analy

In [4]:
import pandas as pd
data = pd.read_csv('./esox.csv')

In [5]:
data

,read_id,basecall_pos,kmers,label,class_0,class_1
0,5a74dba4-271f-4c99-97f0-b6b51b172ba2,714,CTTGATC,0,0.998817,0.001183
1,79a8d96d-5c29-46cf-9cfa-782c8e944d8c,236,GAAGCTT,0,0.999877,0.000123
2,c2337f12-6162-4c66-b35a-c9280e90c583,101,CAAGAAT,1,0.999984,0.000016
3,dd96e535-46de-49f4-b9a8-7ce52554904f,24,CAAGAAG,0,0.992193,0.007807
4,f2952e4d-483e-4a81-8a96-779b2005eddc,131,AGGGTTC,0,0.999998,0.000002
...,...,...,...,...,...,...
223810,a13cf628-5100-4c87-9c11-76a23b067e35,222,CAGGGTT,0,0.999257,0.000743
223811,bb1f2a04-9e90-4237-8b6a-cabc78101609,84,CAGGGTT,0,0.999764,0.000236
223812,014b8c79-8281-4eb6-ad51-3277dd1787dc,80,TCAGGAA,0,0.999194,0.000806
223813,03abccee-fbf8-4fd7-b659-4728ea697886,300,CAAGAAG,0,0.999589,0.000411
223814,cea385e5-dafd-42b0-91d3-afcaeec819fd,959,AGGGTTC,0,0.999994,0.000006

In [8]:
data['label'].value_counts()

label
0    180071
1     43744
Name: count, dtype: int64

In [42]:
TN = data[(data['class_0']>data['class_1']) & (data['label']==0)]
TP = data[(data['class_0']<=data['class_1']) & (data['label']==1)]
FN = data[(data['class_0']>data['class_1']) & (data['label']==1)]
FP = data[(data['class_0']<=data['class_1']) & (data['label']==0)]

In [43]:
TN

,read_id,basecall_pos,kmers,label,class_0,class_1
0,5a74dba4-271f-4c99-97f0-b6b51b172ba2,714,CTTGATC,0,0.998817,0.001183
1,79a8d96d-5c29-46cf-9cfa-782c8e944d8c,236,GAAGCTT,0,0.999877,0.000123
3,dd96e535-46de-49f4-b9a8-7ce52554904f,24,CAAGAAG,0,0.992193,0.007807
4,f2952e4d-483e-4a81-8a96-779b2005eddc,131,AGGGTTC,0,0.999998,0.000002
5,a4ba68dc-6c75-48f6-86bf-285822e8fefa,576,TACGCAC,0,0.999997,0.000003
...,...,...,...,...,...,...
223810,a13cf628-5100-4c87-9c11-76a23b067e35,222,CAGGGTT,0,0.999257,0.000743
223811,bb1f2a04-9e90-4237-8b6a-cabc78101609,84,CAGGGTT,0,0.999764,0.000236
223812,014b8c79-8281-4eb6-ad51-3277dd1787dc,80,TCAGGAA,0,0.999194,0.000806
223813,03abccee-fbf8-4fd7-b659-4728ea697886,300,CAAGAAG,0,0.999589,0.000411
223814,cea385e5-dafd-42b0-91d3-afcaeec819fd,959,AGGGTTC,0,0.999994,0.000006

In [44]:
recall = len(TP)/(len(TP)+len(FN))
print(f'recall: {recall}')

recall: 0.3243644842721288

In [45]:
spec = len(TN)/(len(TN)+len(FP))
print(f'spec: {spec}')

spec: 0.9989726274636116

In [39]:
FP

,read_id,basecall_pos,kmers,label,class_0,class_1
0,5a74dba4-271f-4c99-97f0-b6b51b172ba2,714,CTTGATC,0,0.998817,0.001183
1,79a8d96d-5c29-46cf-9cfa-782c8e944d8c,236,GAAGCTT,0,0.999877,0.000123
2,c2337f12-6162-4c66-b35a-c9280e90c583,101,CAAGAAT,1,0.999984,0.000016
3,dd96e535-46de-49f4-b9a8-7ce52554904f,24,CAAGAAG,0,0.992193,0.007807
4,f2952e4d-483e-4a81-8a96-779b2005eddc,131,AGGGTTC,0,0.999998,0.000002
...,...,...,...,...,...,...
223810,a13cf628-5100-4c87-9c11-76a23b067e35,222,CAGGGTT,0,0.999257,0.000743
223811,bb1f2a04-9e90-4237-8b6a-cabc78101609,84,CAGGGTT,0,0.999764,0.000236
223812,014b8c79-8281-4eb6-ad51-3277dd1787dc,80,TCAGGAA,0,0.999194,0.000806
223813,03abccee-fbf8-4fd7-b659-4728ea697886,300,CAAGAAG,0,0.999589,0.000411
223814,cea385e5-dafd-42b0-91d3-afcaeec819fd,959,AGGGTTC,0,0.999994,0.000006

In [33]:
N = len(TN)+len(FP)
N

403886

In [34]:
P = len(TP)+len(FN)
P

43744

In [40]:
len(TN)

194260

In [41]:
FP['label'].value_counts()

label
0    180071
1     29555
Name: count, dtype: int64